name: Update Homebrew Tap

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 0.1.7)'
        required: true

jobs:
  update-tap:
    name: Generate formula and open PR to tap
    runs-on: ubuntu-latest
    env:
      TAP_REPO: ${{ vars.TAP_REPO || 'luw2007/homebrew-tap' }}
      TAP_DEFAULT_BRANCH: ${{ vars.TAP_DEFAULT_BRANCH || 'main' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Derive version from tag
        id: ver
        env:
          VERSION_INPUT: ${{ github.event.inputs.version }}
        run: |
          tag="${VERSION_INPUT:-}"
          if [ -z "$tag" ]; then
            tag="${GITHUB_REF_NAME:-}"
          fi
          if [ -z "$tag" ]; then
            tag="${{ github.event.release.tag_name }}"
          fi
          tag="${tag#refs/tags/}"
          if [ -z "$tag" ]; then
            echo "::error::Unable to determine tag/version" >&2; exit 1; fi
          if [[ "$tag" != v* ]]; then
            tag="v${tag}"
          fi
          version="${tag#v}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Show version
        run: echo "Releasing version ${{ steps.ver.outputs.version }} (tag ${{ steps.ver.outputs.tag }})"

      - name: Prepare environment
        run: sudo apt-get update && sudo apt-get install -y curl git jq

      - name: Clone tap repository
        env:
          TOKEN: ${{ secrets.TAP_PUSH_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${TOKEN:-}" ]; then
            echo "::error::Missing TAP_PUSH_TOKEN secret with write access to $TAP_REPO"; exit 1; fi
          TAP_DIR="$RUNNER_TEMP/homebrew-tap"
          git clone "https://x-access-token:${TOKEN}@github.com/${TAP_REPO}.git" "$TAP_DIR"
          echo "TAP_DIR=$TAP_DIR" >> $GITHUB_ENV

      - name: Generate Formula (with sha256)
        run: |
          bash package/gen_formula.sh --version "${{ steps.ver.outputs.version }}" --tap-dir "$TAP_DIR"

      - name: Commit and push branch
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          TOKEN: ${{ secrets.TAP_PUSH_TOKEN }}
        run: |
          set -euo pipefail
          cd "$TAP_DIR"
          BRANCH="tap/update-dt-${{ steps.ver.outputs.version }}"
          git checkout -B "$BRANCH"
          git add Formula/dt.rb
          if git diff --cached --quiet; then
            echo "No changes to commit."; exit 0; fi
          git commit -m "feat(dt): update formula to v${{ steps.ver.outputs.version }}"
          git push -f origin "$BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Open Pull Request
        if: env.BRANCH != ''
        env:
          TOKEN: ${{ secrets.TAP_PUSH_TOKEN }}
        run: |
          set -euo pipefail
          title="dt ${{ steps.ver.outputs.version }}"
          body=$'Auto-generated by update-tap workflow.
          - Updates Formula/dt.rb to the latest tag.
          - Generated with package/gen_formula.sh (computes sha256 from tag tarball).'
          api="https://api.github.com/repos/${TAP_REPO}/pulls"
          data=$(jq -n \
            --arg title "$title" \
            --arg head "$BRANCH" \
            --arg base "$TAP_DEFAULT_BRANCH" \
            --arg body "$body" \
            '{title:$title, head:$head, base:$base, body:$body}')
          curl -sS -H "Authorization: token ${TOKEN}" -H "Accept: application/vnd.github+json" \
            -d "$data" "$api" || true
